steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloudrunteste-353917/combatiq-analyzer', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cloudrunteste-353917/combatiq-analyzer']
# Deploy container image to Cloud Run
#- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#  entrypoint: gcloud
#  args: ['run', 'deploy', 'combatiq-new', '--image', 'gcr.io/cloudrunteste-353917/combatiq-new', '--region', 'europe-west1']
images:
- gcr.io/cloudrunteste-353917/combatiq-analyzer
